spring:
  datasource:
    url: jdbc:mysql://192.168.0.211:3306/main?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
    username: ops
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 192.168.0.205
    port: 6379

  dubbo:
    application:
      name: spring-boot-demo
    registry:
      address: zookeeper://192.168.0.242:2181?backup=192.168.0.205:2181,192.168.0.243:2181
    protocol:
      name: dubbo
      port: 20880
    scan: org.allen